import mongoose, { Document, Schema } from 'mongoose';

// ---------- ENUMS ----------
export enum TaskType {
  FOOD = 'food',
  HOMEWORK = 'homework',
  EMAIL = 'email',
  MEETING = 'meeting',
  PROJECT = 'project',
  PERSONAL = 'personal',
  WORK = 'work',
  HEALTH = 'health',
  SOCIAL = 'social',
  OTHER = 'other',
}

export enum TaskPriority {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  URGENT = 'urgent',
}

export enum TaskStatus {
  PENDING = 'pending',
  IN_PROGRESS = 'in_progress',
  COMPLETED = 'completed',
  CANCELLED = 'cancelled',
}

// ---------- BASE TASK INTERFACE ----------
export interface IBaseTask extends Document {
  // Core task fields
  title: string;
  description?: string;
  taskType: TaskType;
  priority: TaskPriority;
  status: TaskStatus;
  dueDate?: Date;
  startDate?: Date;
  completedAt?: Date;
  estimatedDuration?: number; // in minutes
  actualDuration?: number; // in minutes
  tags: string[];
  
  // User relationships
  assignee: mongoose.Types.ObjectId; // User who owns the task
  assignedBy?: mongoose.Types.ObjectId; // User who assigned the task (if different from assignee)
  collaborators: mongoose.Types.ObjectId[]; // Users who can help with the task
  
  // Task organization
  location?: string;
  isRecurring: boolean;
  recurringPattern?: {
    frequency: 'daily' | 'weekly' | 'monthly' | 'yearly';
    interval: number; // every X days/weeks/months/years
    daysOfWeek?: number[]; // 0-6 for Sunday-Saturday (for weekly)
    dayOfMonth?: number; // 1-31 (for monthly)
    endDate?: Date;
  };
  parentTask?: mongoose.Types.ObjectId; // For subtasks
  subtasks: mongoose.Types.ObjectId[]; // Array of subtask IDs
  
  // Task content
  attachments: {
    filename: string;
    url: string;
    uploadedAt: Date;
  }[];
  notes: {
    content: string;
    createdAt: Date;
    createdBy: mongoose.Types.ObjectId;
  }[];
  reminders: {
    date: Date;
    message: string;
    isSent: boolean;
  }[];
  
  // XP and gamification
  xpValue: number;
  autoGenerated?: boolean; // if AI created it
  
  // Personal task fields (optional for all tasks)
  personalCategory?: 'health' | 'fitness' | 'hobby' | 'learning' | 'travel' | 'family' | 'finance' | 'home' | 'other';
  isPrivate?: boolean;
  personalNotes?: string;
  moodBefore?: string;
  moodAfter?: string;
  energyLevel?: 1 | 2 | 3 | 4 | 5; // 1 = very low, 5 = very high
  weatherDependent?: boolean;
  weatherCondition?: string;
  seasonality?: string[]; // e.g., ['spring', 'summer']
  personalGoals?: string[];
  reflection?: string;
  photos?: string[]; // URLs to photos
  cost?: number;
  actualCost?: number;
  
  createdAt: Date;
  updatedAt: Date;
}

// ---------- BASE TASK SCHEMA ----------
const BaseTaskSchema = new Schema({
  title: {
    type: String,
    required: [true, 'Please add a task title'],
    trim: true,
    maxlength: [200, 'Title cannot be more than 200 characters']
  },
  description: {
    type: String,
    trim: true,
    maxlength: [1000, 'Description cannot be more than 1000 characters']
  },
  taskType: {
    type: String,
    enum: Object.values(TaskType),
    required: [true, 'Please specify task type'],
    default: TaskType.OTHER
  },
  priority: {
    type: String,
    enum: Object.values(TaskPriority),
    default: TaskPriority.MEDIUM
  },
  status: {
    type: String,
    enum: Object.values(TaskStatus),
    default: TaskStatus.PENDING
  },
  dueDate: {
    type: Date
  },
  startDate: {
    type: Date
  },
  completedAt: {
    type: Date
  },
  estimatedDuration: {
    type: Number,
    min: [1, 'Duration must be at least 1 minute']
  },
  actualDuration: {
    type: Number,
    min: [1, 'Duration must be at least 1 minute']
  },
  tags: [{
    type: String,
    trim: true,
    maxlength: [50, 'Tag cannot be more than 50 characters']
  }],
  assignee: {
    type: Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  assignedBy: {
    type: Schema.Types.ObjectId,
    ref: 'User'
  },
  collaborators: [{
    type: Schema.Types.ObjectId,
    ref: 'User'
  }],
  location: {
    type: String,
    trim: true,
    maxlength: [200, 'Location cannot be more than 200 characters']
  },
  isRecurring: {
    type: Boolean,
    default: false
  },
  recurringPattern: {
    frequency: {
      type: String,
      enum: ['daily', 'weekly', 'monthly', 'yearly']
    },
    interval: {
      type: Number,
      min: [1, 'Interval must be at least 1']
    },
    daysOfWeek: [{
      type: Number,
      min: 0,
      max: 6
    }],
    dayOfMonth: {
      type: Number,
      min: 1,
      max: 31
    },
    endDate: {
      type: Date
    }
  },
  parentTask: {
    type: Schema.Types.ObjectId,
    ref: 'Task'
  },
  subtasks: [{
    type: Schema.Types.ObjectId,
    ref: 'Task'
  }],
  attachments: [{
    filename: {
      type: String,
      required: true
    },
    url: {
      type: String,
      required: true
    },
    uploadedAt: {
      type: Date,
      default: Date.now
    }
  }],
  notes: [{
    content: {
      type: String,
      required: true,
      maxlength: [500, 'Note cannot be more than 500 characters']
    },
    createdAt: {
      type: Date,
      default: Date.now
    },
    createdBy: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true
    }
  }],
  reminders: [{
    date: {
      type: Date,
      required: true
    },
    message: {
      type: String,
      maxlength: [200, 'Reminder message cannot be more than 200 characters']
    },
    isSent: {
      type: Boolean,
      default: false
    }
  }],
  xpValue: {
    type: Number,
    default: 10,
    min: [0, 'XP value cannot be negative']
  },
  autoGenerated: {
    type: Boolean,
    default: false
  },
  
  // Personal task fields (optional for all tasks)
  personalCategory: {
    type: String,
    enum: ['health', 'fitness', 'hobby', 'learning', 'travel', 'family', 'finance', 'home', 'other']
  },
  isPrivate: {
    type: Boolean,
    default: false
  },
  personalNotes: {
    type: String,
    trim: true,
    maxlength: [1000, 'Personal notes cannot be more than 1000 characters']
  },
  moodBefore: {
    type: String,
    trim: true,
    maxlength: [100, 'Mood description cannot be more than 100 characters']
  },
  moodAfter: {
    type: String,
    trim: true,
    maxlength: [100, 'Mood description cannot be more than 100 characters']
  },
  energyLevel: {
    type: Number,
    enum: [1, 2, 3, 4, 5],
    default: 3
  },
  weatherDependent: {
    type: Boolean,
    default: false
  },
  weatherCondition: {
    type: String,
    trim: true,
    maxlength: [50, 'Weather condition cannot be more than 50 characters']
  },
  seasonality: [{
    type: String,
    enum: ['spring', 'summer', 'fall', 'winter'],
    trim: true
  }],
  personalGoals: [{
    type: String,
    trim: true,
    maxlength: [200, 'Personal goal cannot be more than 200 characters']
  }],
  reflection: {
    type: String,
    trim: true,
    maxlength: [1000, 'Reflection cannot be more than 1000 characters']
  },
  photos: [{
    type: String,
    trim: true
  }],
  cost: {
    type: Number,
    min: [0, 'Cost cannot be negative']
  },
  actualCost: {
    type: Number,
    min: [0, 'Actual cost cannot be negative']
  }
}, {
  timestamps: true
});

// Indexes for better query performance
BaseTaskSchema.index({ assignee: 1, status: 1 });
BaseTaskSchema.index({ dueDate: 1 });
BaseTaskSchema.index({ taskType: 1 });
BaseTaskSchema.index({ priority: 1 });
BaseTaskSchema.index({ tags: 1 });

// Personal task indexes
BaseTaskSchema.index({ assignee: 1, personalCategory: 1 });
BaseTaskSchema.index({ assignee: 1, isPrivate: 1 });
BaseTaskSchema.index({ energyLevel: 1 });
BaseTaskSchema.index({ seasonality: 1 });

// Virtual for checking if task is overdue
BaseTaskSchema.virtual('isOverdue').get(function() {
  return this.dueDate && this.dueDate < new Date() && this.status !== TaskStatus.COMPLETED;
});

// Virtual for checking if task affects mood positively
BaseTaskSchema.virtual('improvesMood').get(function() {
  if (!this.moodBefore || !this.moodAfter) return null;
  // Simple mood improvement check - can be enhanced with sentiment analysis
  const positiveMoods = ['happy', 'energized', 'satisfied', 'accomplished', 'relaxed'];
  return positiveMoods.some(mood => this.moodAfter!.toLowerCase().includes(mood));
});

// Virtual for checking if task is weather appropriate
BaseTaskSchema.virtual('isWeatherAppropriate').get(function() {
  if (!this.weatherDependent || !this.weatherCondition) return true;
  // This would integrate with weather API in real implementation
  return true; // Placeholder
});

// Pre-save middleware to set completedAt when status changes to completed
BaseTaskSchema.pre('save', function(next) {
  if (this.isModified('status') && this.status === TaskStatus.COMPLETED && !this.completedAt) {
    this.completedAt = new Date();
  }
  next();
});

// Method to add a note
BaseTaskSchema.methods['addNote'] = function(content: string, userId: string) {
  this['notes'].push({
    content,
    createdBy: userId
  });
  return this['save']();
};

// Method to add a reminder
BaseTaskSchema.methods['addReminder'] = function(date: Date, message?: string) {
  this['reminders'].push({
    date,
    message: message || `Reminder: ${this['title']}`,
    isSent: false
  });
  return this['save']();
};

// Method to add a collaborator
BaseTaskSchema.methods['addCollaborator'] = function(userId: string) {
  if (!this['collaborators'].includes(userId)) {
    this['collaborators'].push(userId);
  }
  return this['save']();
};

// Method to remove a collaborator
BaseTaskSchema.methods['removeCollaborator'] = function(userId: string) {
  this['collaborators'] = this['collaborators'].filter((id: any) => !id.equals(userId));
  return this['save']();
};

// Personal task methods
BaseTaskSchema.methods['addPersonalGoal'] = function(goal: string) {
  if (!this['personalGoals']) {
    this['personalGoals'] = [];
  }
  if (!this['personalGoals'].includes(goal)) {
    this['personalGoals'].push(goal);
  }
  return this['save']();
};

BaseTaskSchema.methods['addPhoto'] = function(photoUrl: string) {
  if (!this['photos']) {
    this['photos'] = [];
  }
  if (!this['photos'].includes(photoUrl)) {
    this['photos'].push(photoUrl);
  }
  return this['save']();
};

BaseTaskSchema.methods['updateMood'] = function(mood: string, isAfter: boolean = false) {
  if (isAfter) {
    this['moodAfter'] = mood;
  } else {
    this['moodBefore'] = mood;
  }
  return this['save']();
};

export { BaseTaskSchema };
export default BaseTaskSchema;
