// Frontend types based on backend FoodTask model
import { IBaseTask, TaskType } from './BaseTask';

// ---------- FOOD TASK INTERFACE ----------
export interface IFoodTask extends IBaseTask {
  // Food-specific fields
  foodName: string;
  category: 'Breakfast' | 'Lunch' | 'Dinner' | 'Snack' | 'Drink';
  calories: number;
  protein?: number;
  carbs?: number;
  fats?: number;
  sugar?: number;
  fiber?: number;
  cost?: number; // in USD
  cookTime?: number; // in minutes
  ingredients?: string[];
  healthRating?: 1 | 2 | 3 | 4 | 5; // Poor to Superfood
  moodAfterEating?: string;
  source?: string; // e.g. "Home-cooked", "Restaurant", "Delivery"
  image?: string;
  loggedAt: Date;
  aiSuggestions?: {
    substitute?: string;
    tip?: string;
  };
}

// ---------- FRONTEND-SPECIFIC TYPES ----------
export interface FoodTask {
  _id: string;
  title: string;
  description?: string;
  taskType: TaskType.FOOD;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
  dueDate?: Date;
  startDate?: Date;
  completedAt?: Date;
  estimatedDuration?: number;
  actualDuration?: number;
  tags: string[];
  assignee: string;
  assignedBy?: string;
  collaborators: string[];
  location?: string;
  isRecurring: boolean;
  recurringPattern?: {
    frequency: 'daily' | 'weekly' | 'monthly' | 'yearly';
    interval: number;
    daysOfWeek?: number[];
    dayOfMonth?: number;
    endDate?: Date;
  };
  parentTask?: string;
  subtasks: string[];
  attachments: Array<{
    filename: string;
    url: string;
    uploadedAt: Date;
  }>;
  notes: Array<{
    content: string;
    createdAt: Date;
    createdBy: string;
  }>;
  reminders: Array<{
    date: Date;
    message: string;
    isSent: boolean;
  }>;
  xpValue: number;
  autoGenerated?: boolean;
  personalCategory?: 'health' | 'fitness' | 'hobby' | 'learning' | 'travel' | 'family' | 'finance' | 'home' | 'other';
  isPrivate?: boolean;
  personalNotes?: string;
  moodBefore?: string;
  moodAfter?: string;
  energyLevel?: 1 | 2 | 3 | 4 | 5;
  weatherDependent?: boolean;
  weatherCondition?: string;
  seasonality?: string[];
  personalGoals?: string[];
  reflection?: string;
  photos?: string[];
  cost?: number;
  actualCost?: number;
  createdAt: Date;
  updatedAt: Date;
  
  // Food-specific fields
  foodName: string;
  category: 'Breakfast' | 'Lunch' | 'Dinner' | 'Snack' | 'Drink';
  calories: number;
  protein?: number;
  carbs?: number;
  fats?: number;
  sugar?: number;
  fiber?: number;
  cookTime?: number; // in minutes
  ingredients?: string[];
  healthRating?: 1 | 2 | 3 | 4 | 5; // Poor to Superfood
  moodAfterEating?: string;
  source?: string; // e.g. "Home-cooked", "Restaurant", "Delivery"
  image?: string;
  loggedAt: Date;
  aiSuggestions?: {
    substitute?: string;
    tip?: string;
  };
}
