// Frontend types for Health tasks
import { IBaseTask, TaskType } from './BaseTask';

// ---------- HEALTH TASK INTERFACE ----------
export interface IHealthTask extends IBaseTask {
  // Health-specific fields
  healthCategory: 'exercise' | 'medical' | 'nutrition' | 'mental_health' | 'sleep' | 'preventive_care' | 'other';
  healthGoal?: string;
  targetValue?: number;
  currentValue?: number;
  unit?: string; // e.g., 'minutes', 'steps', 'calories', 'mg'
  healthProvider?: string; // Doctor, trainer, etc.
  appointmentDate?: Date;
  medication?: string[];
  symptoms?: string[];
  vitalSigns?: {
    bloodPressure?: string;
    heartRate?: number;
    temperature?: number;
    weight?: number;
    height?: number;
  };
  healthNotes?: string;
  followUpDate?: Date;
  isRecurring: boolean;
}

// ---------- FRONTEND-SPECIFIC TYPES ----------
export interface HealthTask {
  _id: string;
  title: string;
  description?: string;
  taskType: TaskType.HEALTH;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
  dueDate?: Date;
  startDate?: Date;
  completedAt?: Date;
  estimatedDuration?: number;
  actualDuration?: number;
  tags: string[];
  assignee: string;
  assignedBy?: string;
  collaborators: string[];
  location?: string;
  isRecurring: boolean;
  recurringPattern?: {
    frequency: 'daily' | 'weekly' | 'monthly' | 'yearly';
    interval: number;
    daysOfWeek?: number[];
    dayOfMonth?: number;
    endDate?: Date;
  };
  parentTask?: string;
  subtasks: string[];
  attachments: Array<{
    filename: string;
    url: string;
    uploadedAt: Date;
  }>;
  notes: Array<{
    content: string;
    createdAt: Date;
    createdBy: string;
  }>;
  reminders: Array<{
    date: Date;
    message: string;
    isSent: boolean;
  }>;
  xpValue: number;
  autoGenerated?: boolean;
  personalCategory?: 'health' | 'fitness' | 'hobby' | 'learning' | 'travel' | 'family' | 'finance' | 'home' | 'other';
  isPrivate?: boolean;
  personalNotes?: string;
  moodBefore?: string;
  moodAfter?: string;
  energyLevel?: 1 | 2 | 3 | 4 | 5;
  weatherDependent?: boolean;
  weatherCondition?: string;
  seasonality?: string[];
  personalGoals?: string[];
  reflection?: string;
  photos?: string[];
  cost?: number;
  actualCost?: number;
  createdAt: Date;
  updatedAt: Date;
  
  // Health-specific fields
  healthCategory: 'exercise' | 'medical' | 'nutrition' | 'mental_health' | 'sleep' | 'preventive_care' | 'other';
  healthGoal?: string;
  targetValue?: number;
  currentValue?: number;
  unit?: string; // e.g., 'minutes', 'steps', 'calories', 'mg'
  healthProvider?: string; // Doctor, trainer, etc.
  appointmentDate?: Date;
  medication?: string[];
  symptoms?: string[];
  vitalSigns?: {
    bloodPressure?: string;
    heartRate?: number;
    temperature?: number;
    weight?: number;
    height?: number;
  };
  healthNotes?: string;
  followUpDate?: Date;
}
