// Frontend types based on backend MeetingTask model
import { IBaseTask, TaskType } from './BaseTask';

// ---------- MEETING TASK INTERFACE ----------
export interface IMeetingTask extends IBaseTask {
  // Meeting-specific fields
  meetingType: 'team_meeting' | 'one_on_one' | 'client_meeting' | 'interview' | 'presentation' | 'workshop' | 'other';
  attendees: string[]; // User IDs of attendees
  attendeeEmails?: string[]; // External attendees
  meetingRoom?: string;
  meetingLink?: string; // For virtual meetings
  agenda?: string[];
  meetingNotes?: string;
  actionItems?: {
    item: string;
    assignee: string;
    dueDate?: Date;
    completed: boolean;
  }[];
  meetingDuration: number; // in minutes
  actualDuration?: number; // in minutes
  meetingOutcome?: 'successful' | 'needs_follow_up' | 'cancelled' | 'rescheduled';
  nextMeetingDate?: Date;
  recurringMeeting?: boolean;
  meetingSeriesId?: string; // For recurring meetings
}

// ---------- FRONTEND-SPECIFIC TYPES ----------
export interface MeetingTask {
  _id: string;
  title: string;
  description?: string;
  taskType: TaskType.MEETING;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
  dueDate?: Date;
  startDate?: Date;
  completedAt?: Date;
  estimatedDuration?: number;
  tags: string[];
  assignee: string;
  assignedBy?: string;
  collaborators: string[];
  location?: string;
  isRecurring: boolean;
  recurringPattern?: {
    frequency: 'daily' | 'weekly' | 'monthly' | 'yearly';
    interval: number;
    daysOfWeek?: number[];
    dayOfMonth?: number;
    endDate?: Date;
  };
  parentTask?: string;
  subtasks: string[];
  attachments: Array<{
    filename: string;
    url: string;
    uploadedAt: Date;
  }>;
  notes: Array<{
    content: string;
    createdAt: Date;
    createdBy: string;
  }>;
  reminders: Array<{
    date: Date;
    message: string;
    isSent: boolean;
  }>;
  xpValue: number;
  autoGenerated?: boolean;
  personalCategory?: 'health' | 'fitness' | 'hobby' | 'learning' | 'travel' | 'family' | 'finance' | 'home' | 'other';
  isPrivate?: boolean;
  personalNotes?: string;
  moodBefore?: string;
  moodAfter?: string;
  energyLevel?: 1 | 2 | 3 | 4 | 5;
  weatherDependent?: boolean;
  weatherCondition?: string;
  seasonality?: string[];
  personalGoals?: string[];
  reflection?: string;
  photos?: string[];
  cost?: number;
  actualCost?: number;
  createdAt: Date;
  updatedAt: Date;
  
  // Meeting-specific fields
  meetingType: 'team_meeting' | 'one_on_one' | 'client_meeting' | 'interview' | 'presentation' | 'workshop' | 'other';
  attendees: string[]; // User IDs of attendees
  attendeeEmails?: string[]; // External attendees
  meetingRoom?: string;
  meetingLink?: string; // For virtual meetings
  agenda?: string[];
  meetingNotes?: string;
  actionItems?: {
    item: string;
    assignee: string;
    dueDate?: Date;
    completed: boolean;
  }[];
  meetingDuration: number; // in minutes
  actualDuration?: number; // in minutes
  meetingOutcome?: 'successful' | 'needs_follow_up' | 'cancelled' | 'rescheduled';
  nextMeetingDate?: Date;
  recurringMeeting?: boolean;
  meetingSeriesId?: string; // For recurring meetings
}
