// Frontend types based on backend ProjectTask model
import { IBaseTask, TaskType } from './BaseTask';

// ---------- PROJECT TASK INTERFACE ----------
export interface IProjectTask extends IBaseTask {
  // Project-specific fields
  projectName: string;
  projectPhase: 'planning' | 'development' | 'testing' | 'deployment' | 'maintenance' | 'completed';
  projectType: 'web_app' | 'mobile_app' | 'desktop_app' | 'api' | 'database' | 'infrastructure' | 'research' | 'other';
  teamMembers: string[];
  projectManager?: string;
  budget?: number;
  actualCost?: number;
  technologies: string[]; // Tech stack
  projectGoals: string[];
  deliverables: string[];
  milestones: {
    name: string;
    dueDate: Date;
    completed: boolean;
    completedAt?: Date;
  }[];
  projectStatus: 'on_track' | 'at_risk' | 'delayed' | 'cancelled';
  riskFactors?: string[];
  dependencies?: string[]; // Other project dependencies
  clientName?: string;
  clientContact?: string;
}

// ---------- FRONTEND-SPECIFIC TYPES ----------
export interface ProjectTask {
  _id: string;
  title: string;
  description?: string;
  taskType: TaskType.PROJECT;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
  dueDate?: Date;
  startDate?: Date;
  completedAt?: Date;
  estimatedDuration?: number;
  actualDuration?: number;
  tags: string[];
  assignee: string;
  assignedBy?: string;
  collaborators: string[];
  location?: string;
  isRecurring: boolean;
  recurringPattern?: {
    frequency: 'daily' | 'weekly' | 'monthly' | 'yearly';
    interval: number;
    daysOfWeek?: number[];
    dayOfMonth?: number;
    endDate?: Date;
  };
  parentTask?: string;
  subtasks: string[];
  attachments: Array<{
    filename: string;
    url: string;
    uploadedAt: Date;
  }>;
  notes: Array<{
    content: string;
    createdAt: Date;
    createdBy: string;
  }>;
  reminders: Array<{
    date: Date;
    message: string;
    isSent: boolean;
  }>;
  xpValue: number;
  autoGenerated?: boolean;
  personalCategory?: 'health' | 'fitness' | 'hobby' | 'learning' | 'travel' | 'family' | 'finance' | 'home' | 'other';
  isPrivate?: boolean;
  personalNotes?: string;
  moodBefore?: string;
  moodAfter?: string;
  energyLevel?: 1 | 2 | 3 | 4 | 5;
  weatherDependent?: boolean;
  weatherCondition?: string;
  seasonality?: string[];
  personalGoals?: string[];
  reflection?: string;
  photos?: string[];
  cost?: number;
  actualCost?: number;
  createdAt: Date;
  updatedAt: Date;
  
  // Project-specific fields
  projectName: string;
  projectPhase: 'planning' | 'development' | 'testing' | 'deployment' | 'maintenance' | 'completed';
  projectType: 'web_app' | 'mobile_app' | 'desktop_app' | 'api' | 'database' | 'infrastructure' | 'research' | 'other';
  teamMembers: string[];
  projectManager?: string;
  budget?: number;
  technologies: string[]; // Tech stack
  projectGoals: string[];
  deliverables: string[];
  milestones: {
    name: string;
    dueDate: Date;
    completed: boolean;
    completedAt?: Date;
  }[];
  projectStatus: 'on_track' | 'at_risk' | 'delayed' | 'cancelled';
  riskFactors?: string[];
  dependencies?: string[]; // Other project dependencies
  clientName?: string;
  clientContact?: string;
}
