// Frontend types for Social tasks
import { IBaseTask, TaskType } from './BaseTask';

// ---------- SOCIAL TASK INTERFACE ----------
export interface ISocialTask extends IBaseTask {
  // Social-specific fields
  socialCategory: 'networking' | 'event' | 'volunteer' | 'community' | 'family' | 'friends' | 'other';
  eventType?: 'party' | 'meeting' | 'conference' | 'workshop' | 'dinner' | 'activity' | 'other';
  attendees?: {
    name: string;
    relationship: string;
    contact?: string;
  }[];
  eventLocation?: {
    name: string;
    address?: string;
    coordinates?: {
      lat: number;
      lng: number;
    };
  };
  socialGoals?: string[];
  networkingOpportunities?: string[];
  socialNotes?: string;
  followUpActions?: string[];
  socialImpact?: 'low' | 'medium' | 'high';
}

// ---------- FRONTEND-SPECIFIC TYPES ----------
export interface SocialTask {
  _id: string;
  title: string;
  description?: string;
  taskType: TaskType.SOCIAL;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
  dueDate?: Date;
  startDate?: Date;
  completedAt?: Date;
  estimatedDuration?: number;
  actualDuration?: number;
  tags: string[];
  assignee: string;
  assignedBy?: string;
  collaborators: string[];
  location?: string;
  isRecurring: boolean;
  recurringPattern?: {
    frequency: 'daily' | 'weekly' | 'monthly' | 'yearly';
    interval: number;
    daysOfWeek?: number[];
    dayOfMonth?: number;
    endDate?: Date;
  };
  parentTask?: string;
  subtasks: string[];
  attachments: Array<{
    filename: string;
    url: string;
    uploadedAt: Date;
  }>;
  notes: Array<{
    content: string;
    createdAt: Date;
    createdBy: string;
  }>;
  reminders: Array<{
    date: Date;
    message: string;
    isSent: boolean;
  }>;
  xpValue: number;
  autoGenerated?: boolean;
  personalCategory?: 'health' | 'fitness' | 'hobby' | 'learning' | 'travel' | 'family' | 'finance' | 'home' | 'other';
  isPrivate?: boolean;
  personalNotes?: string;
  moodBefore?: string;
  moodAfter?: string;
  energyLevel?: 1 | 2 | 3 | 4 | 5;
  weatherDependent?: boolean;
  weatherCondition?: string;
  seasonality?: string[];
  personalGoals?: string[];
  reflection?: string;
  photos?: string[];
  cost?: number;
  actualCost?: number;
  createdAt: Date;
  updatedAt: Date;
  
  // Social-specific fields
  socialCategory: 'networking' | 'event' | 'volunteer' | 'community' | 'family' | 'friends' | 'other';
  eventType?: 'party' | 'meeting' | 'conference' | 'workshop' | 'dinner' | 'activity' | 'other';
  attendees?: {
    name: string;
    relationship: string;
    contact?: string;
  }[];
  eventLocation?: {
    name: string;
    address?: string;
    coordinates?: {
      lat: number;
      lng: number;
    };
  };
  socialGoals?: string[];
  networkingOpportunities?: string[];
  socialNotes?: string;
  followUpActions?: string[];
  socialImpact?: 'low' | 'medium' | 'high';
}
