// Frontend types based on backend WorkTask model
import { IBaseTask, TaskType } from './BaseTask';

// ---------- WORK TASK INTERFACE ----------
export interface IWorkTask extends IBaseTask {
  // Work-specific fields
  workCategory: 'development' | 'design' | 'marketing' | 'sales' | 'hr' | 'finance' | 'operations' | 'research' | 'other';
  department?: string;
  manager?: string;
  client?: string;
  projectCode?: string;
  billableHours?: number;
  hourlyRate?: number;
  workPriority: 'low' | 'medium' | 'high' | 'critical';
  deadline: Date; // Required for work tasks
  workStatus: 'not_started' | 'in_progress' | 'review' | 'approved' | 'completed';
  blockers?: string[];
  dependencies?: string[];
  deliverables?: string[];
  workNotes?: string;
  timeTracking?: {
    startTime?: Date;
    endTime?: Date;
    breakTime?: number; // in minutes
    totalTime?: number; // in minutes
  };
  qualityScore?: number; // 1-10 rating
  feedback?: string;
}

// ---------- FRONTEND-SPECIFIC TYPES ----------
export interface WorkTask {
  _id: string;
  title: string;
  description?: string;
  taskType: TaskType.WORK;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
  dueDate?: Date;
  startDate?: Date;
  completedAt?: Date;
  estimatedDuration?: number;
  actualDuration?: number;
  tags: string[];
  assignee: string;
  assignedBy?: string;
  collaborators: string[];
  location?: string;
  isRecurring: boolean;
  recurringPattern?: {
    frequency: 'daily' | 'weekly' | 'monthly' | 'yearly';
    interval: number;
    daysOfWeek?: number[];
    dayOfMonth?: number;
    endDate?: Date;
  };
  parentTask?: string;
  subtasks: string[];
  attachments: Array<{
    filename: string;
    url: string;
    uploadedAt: Date;
  }>;
  notes: Array<{
    content: string;
    createdAt: Date;
    createdBy: string;
  }>;
  reminders: Array<{
    date: Date;
    message: string;
    isSent: boolean;
  }>;
  xpValue: number;
  autoGenerated?: boolean;
  personalCategory?: 'health' | 'fitness' | 'hobby' | 'learning' | 'travel' | 'family' | 'finance' | 'home' | 'other';
  isPrivate?: boolean;
  personalNotes?: string;
  moodBefore?: string;
  moodAfter?: string;
  energyLevel?: 1 | 2 | 3 | 4 | 5;
  weatherDependent?: boolean;
  weatherCondition?: string;
  seasonality?: string[];
  personalGoals?: string[];
  reflection?: string;
  photos?: string[];
  cost?: number;
  actualCost?: number;
  createdAt: Date;
  updatedAt: Date;
  
  // Work-specific fields
  workCategory: 'development' | 'design' | 'marketing' | 'sales' | 'hr' | 'finance' | 'operations' | 'research' | 'other';
  department?: string;
  manager?: string;
  client?: string;
  projectCode?: string;
  billableHours?: number;
  hourlyRate?: number;
  workPriority: 'low' | 'medium' | 'high' | 'critical';
  deadline: Date; // Required for work tasks
  workStatus: 'not_started' | 'in_progress' | 'review' | 'approved' | 'completed';
  blockers?: string[];
  dependencies?: string[];
  deliverables?: string[];
  workNotes?: string;
  timeTracking?: {
    startTime?: Date;
    endTime?: Date;
    breakTime?: number; // in minutes
    totalTime?: number; // in minutes
  };
  qualityScore?: number; // 1-10 rating
  feedback?: string;
}
